[package]
name = "shared_types"
version = "0.1.0"
edition = "2024"

[dependencies]

sqlx = { version = "0.7", features = ["runtime-tokio", "mysql"] }

serde = { version = "1.0", features = ["derive"] }